/* dp_xyzaddrbookstruct.hpp
   Generated by spxml2struct from F:\backup\spdatapickle\spdatapickle\addrbook.xml

   !!! DO NOT EDIT !!!

*/

#ifndef __dp_xyzaddrbookstruct_hpp__
#define __dp_xyzaddrbookstruct_hpp__

#include "spdatapickle/spdplib.hpp"

#ifdef __cplusplus
extern "C" {
#endif

enum {
	eTypeXYZPhoneNumber = eTypeSPDPUserDefine + 1,
	eTypeXYZEmail,
	eTypeXYZContact
};

typedef struct tagXYZPhoneNumber {
	char mType[10];
	int32_t mPrimary;
	char * mContent;
} XYZPhoneNumber_t;

typedef struct tagXYZEmail {
	char mType[10];
	char * mAddress;
	char * mNickname;
} XYZEmail_t;

typedef struct tagXYZContact {
	char * mName;
	SP_DPBuffer_t mImage;
	XYZEmail_t * mEmailList;

	int32_t mEmailCount;
	int32_t mPhoneCount;
	XYZPhoneNumber_t * mPhoneList;

	SP_DPInt32List_t mLuckNumber;
} XYZContact_t;

typedef struct tagSP_DPMetaInfo SP_DPMetaInfo_t;
extern SP_DPMetaInfo_t * gXYZAddrbookMetaInfo;

class SP_XmlStringBuffer;
class SP_DataPickle;

class XYZAddrbookPickle {
public:
	XYZAddrbookPickle( int pickleType );
	~XYZAddrbookPickle();

	int pickle( XYZPhoneNumber_t * structure, SP_XmlStringBuffer * buffer );
	int unpickle( SP_XmlStringBuffer * buffer, XYZPhoneNumber_t * structure );

	int pickle( XYZEmail_t * structure, SP_XmlStringBuffer * buffer );
	int unpickle( SP_XmlStringBuffer * buffer, XYZEmail_t * structure );

	int pickle( XYZContact_t * structure, SP_XmlStringBuffer * buffer );
	int unpickle( SP_XmlStringBuffer * buffer, XYZContact_t * structure );


public:
	static int freeFields( XYZPhoneNumber_t & structure );
	static int deepCopy( const XYZPhoneNumber_t * src, XYZPhoneNumber_t * dest );

	static int freeFields( XYZEmail_t & structure );
	static int deepCopy( const XYZEmail_t * src, XYZEmail_t * dest );

	static int freeFields( XYZContact_t & structure );
	static int deepCopy( const XYZContact_t * src, XYZContact_t * dest );


private:
	SP_DataPickle * mImpl;
};


#ifdef __cplusplus
}
#endif

#endif

